codec_union.go, decoder_union_test.go
=> Fixed issue with union ptr decode

.travis.yml, README.md, codec.go, codec_fixed.go, codec_native.go, codec_skip_internal_test.go, decoder_fixed_test.go, decoder_native_test.go, decoder_test.go, encoder_fixed_test.go, encoder_native_test.go, encoder_test.go, protocol.go, protocol_test.go, reader_generic.go, reader_generic_test.go, schema.go, schema_canonical_test.go, schema_internal_test.go, schema_parse.go, schema_test.go
* Added logical type schemas
* Added logical type encoding and decoding
=> Logical Types

ocf/ocf.go, ocf/ocf_test.go
* Added OCF decoder metadata retrieval
* Added OCF encoder metadata setting
=> Add OCF metadata

codec_record.go, encoder_record_test.go
When encoding defaults for unions, they cannot follow the "normal" default case.
Fixes #50
=> fix: union default on map record

codec_native.go, codec_union.go, decoder_union_test.go, encoder_native_test.go, encoder_union_test.go, resolver.go, schema.go
=> fix: logical type encoding in unions

codec_record.go, decoder_record_test.go, encoder_record_test.go, encoder_union_test.go, registry/client.go, types_test.go
The goal is to support embedded structs.
Fixes #100
=> feat: support embedded structs

.golangci.yml, registry/client.go, registry/client_test.go, registry/example_test.go
This adds context support to the registry.
=> registry: add context support

codec_marshaler_test.go, codec_skip_test.go, decoder_array_test.go, decoder_dynamic_test.go, decoder_enum_test.go, decoder_fixed_test.go, decoder_map_test.go, decoder_native_test.go, decoder_record_test.go, decoder_union_test.go, encoder_array_test.go, encoder_enum_test.go, encoder_fixed_test.go, encoder_map_test.go, encoder_native_test.go, encoder_record_test.go, encoder_test.go, encoder_union_test.go, internal/bytesx/reset_test.go, ocf/ocf_test.go, pkg/crc64/crc64_test.go, reader_generic_test.go, reader_skip_test.go, reader_test.go, registry/client_test.go, writer_test.go
=> fix: rework tests

codec_native.go, decoder_native_test.go, encoder_native_test.go, reader_generic.go, schema_test.go
This fixes the timestamp generic logic calculations and the logic date calculations.
Fixes #128 
Fixes #129
=> fix: logical time and date calcs

codec.go, codec_array.go, codec_map.go, codec_union.go, decoder_array_test.go, decoder_map_test.go, decoder_union_test.go, encoder_array_test.go, encoder_map_test.go, encoder_union_test.go
This adds support for recursive types.
Fixes #138
=> feat: support recursive types

ocf/codec.go, ocf/ocf.go, ocf/ocf_test.go
This allows the user to set the OCF deflate compression level.
Fixes #151
=> feat: allow deflate compression level

gen/gen.go, gen/testdata/golden.go
=> fix: nullable slice generation

gen/gen_test.go, internal/bytesx/reset.go, ocf/ocf_test.go, registry/client.go, registry/client_test.go, registry/decoder.go, registry/decoder_internal_test.go, registry/decoder_test.go
This PR cleans up some tests, comments and code
=> fix: cleanup tests and code

README.md, codec.go, codec_convertible_test.go, codec_fixed.go, codec_native.go
=> feat: accept convertible types

ocf/ocf.go, ocf/ocf_test.go
This follows the #265 and allows OCF encoder to have custom value encoder config in contrast with previous behavior of `ocf.Ecoder` always using `avro.DefaultConfig`
=> feat: allow OCF writer to have custom encoder config

.github/workflows/test.yml, .golangci.yml, codec_native.go
This removes repetitive codecs using generics.
=> feat: use generics to remove repetitive codecs

schema.go, schema_json_test.go
=> feat: add properties to JSON output

schema_parse.go, schema_test.go
=> fix: fields reference with a full name

codec_record.go, encoder_record_test.go
=> Fix encoding a struct with a sub-record field default value

schema.go, schema_json_test.go
Avro doc could have multi-line documentation. Schema is not properly JSON encoded
=> allow multi-line doc, and custom fields

README.md
https://github.com/confluentinc/confluent-kafka-go/blob/master/CHANGELOG.md#v250
=> docs: add who uses this

README.md
https://github.com/apache/arrow/blob/main/go/go.mod#L50
=> docs: Add who use case

ocf/ocf.go, ocf/ocf_test.go
Fixes #516 
I wrote a unit test.
=> Add OCF EncoderFunc for setting a single metadata key-val

.github/workflows/test.yml, .golangci.yml
This bumps the linter and handles some Ci failures
=> chore: bump linter

registry/client.go, registry/client_test.go
Adding support for is-compatible-schema endpoint
Closes https://github.com/hamba/avro/issues/547
With unit tests
=> adding support for is-compatible-schema endpoint
