README.md
codec_union.go
decoder_union_test.go
encoder_union_test.go
schema.go
schema_test.go

There is no particular reason not to allow `["string", "null"]` to be seen as nullable and use `*string`. It was an initial design decision that no longer holds muster. Allowing this will reduce the amount of interface casting needed when users do not control the schema.
Fixes #45

feature: allow "reversed" nullable schemas

---

decoder_union_test.go
encoder_union_test.go
resolver.go

This commit fixes the following error that occurs with a map including a boolean type in unions.
```go
package main
import (
"bytes"
"encoding/json"
"log"
"github.com/hamba/avro"
)
var Schema = `{
"type": "record",
"name": "simple",
"namespace": "org.hamba.avro",
"fields" : [
{
"name": "properties",
"type": {
"type": "map",
"values": ["null", "boolean"]
}
}
]
}`
type SimpleRecord struct {
Properties map[string]interface{} `avro:"properties"`
}
func main() {
schema, err := avro.Parse(Schema)
if err != nil {
log.Fatal(err)
}
data := []byte(`
{
"properties": {
"bool": true
}
}
`)
in := SimpleRecord{}
buffer := bytes.NewReader(data)
decoder := json.NewDecoder(buffer)
err = decoder.Decode(&in)
if err != nil {
log.Fatal(err)
}
_, err = avro.Marshal(schema, in)
if err != nil {
log.Fatal(err)
}
} …
```

Register a boolean type

---

codec_map.go
encoder_map_test.go

This commit fixes the following error when encoding a map with more than `blocklength` keys.
```go
package main
import (
"bytes"
"encoding/json"
"log"
"github.com/hamba/avro"
)
var Schema = `{
"type": "record",
"name": "simple",
"namespace": "org.hamba.avro",
"fields" : [
{
"name": "properties",
"type": {
"type": "map",
"values": "int"
}
}
]
}`
type SimpleRecord struct {
Properties map[string]int `avro:"properties"`
}
func main() {
avro.DefaultConfig = avro.Config{
TagKey:               "avro",
BlockLength:          1,
UnionResolutionError: true,
}.Freeze()
schema, err := avro.Parse(Schema)
if err != nil {
log.Fatal(err)
}
data := []byte(`
{
"properties": {
"1": 1,
"2": 2
}
}
`)
in := SimpleRecord{}
buffer := bytes.NewReader(data)
decoder := json.NewDecoder(buffer)
err = …
```

avro: fix map encoding with more than blocklength keys

---

ocf/example_test.go
ocf/ocf.go

It seems that encoder.Close() does not close anything, but it just flushes
the block, i added Flush() kept Close() but added a deprecation note.

ocf: add encoder Flush()

---

README.md
codec.go
codec_marshaler.go
codec_marshaler_test.go
codec_ptr.go
encoder_native_test.go

This adds support for TextMarshaler and TextUnmarshaler.
Fixes #67

avro: add support of TextMarshaler and TextUnmarshaler

---

codec_native.go
decoder_native_test.go
encoder_native_test.go

With really small or large times, timestamps had the potential to overflow an int64.
Fixes: #69

avro: fix timestamp overflows

---

schema.go
schema_internal_test.go

I use this excellent avro library because this is three times faster than linkedin/goavro in my work load.
I found that data-race occurred in multi thread program when I used this library.
That is because `ocf.go` shares `HeaderSchema` instance in `github.com/hamba/avro.(*fingerprinter).Fingerprint()` which is not thread safe.
At first, I attempted to fix `fingerprinter.Fingerprint()` to make it thread safe, but it ended up with less performance.
So, I fix `ocf.go` to avoid sharing a `HeaderSchema` instance.
I write a simple data-race example.
https://github.com/getumen/avro-datarace-example/blob/main/main.go
```
[yoshihiro@MBP] ( ﾟ∀ﾟ)・∵. ~/github/avro-datarace-example % go run -race ./main.go …
```

ocf: fix header schema to avoid data race

---

codec_union.go
encoder_union_test.go

When doing a map union encode, object that are like pointer need their encoders wrapped.
Fixes #82

fix: map union ptr type encoding

---

schema.go
schema_test.go

When getting the schema type name for a union, a reference schema must be dereferenced before finding the name.
Fixes #107

fix: deref the reference schema

---

schema.go
schema_canonical_test.go
schema_json_test.go
schema_parse.go

This adds basic json encoding. It currently misses any field not directly handled by the schema. In order to handle more fields, a refactor of schema parsing and handling is needed, which would be breaking. This is planned for the future.
Fixes #115

feat: add json encoding

---

codec_record.go
decoder_record_test.go
go.mod
go.sum
protocol.go
protocol_test.go
schema.go
schema_compatibility_test.go
schema_internal_test.go
schema_json_test.go
schema_parse.go
schema_test.go

This reworks the schema parsing. In the process aliases are now supported and json serialisation of schemas is greatly improved.

avro: rework schema parsing

---

README.md
codec_record.go

This removes several function calls from the struct codec, leading to better performance.

feat: optimise struct codec

---

protocol_test.go
schema.go
schema_parse.go

I would like to use hamba to validate if a schema conforms to a given set of rules.  One of this rule will check if a documentation block is present and non empty. Unfortunately, the `doc` attribute of a record/field is accessible through properties - as it is a reserved keyword - and there is no dedicated accessor.
Add a dedicated accessor to `RecordSchema` and `Field`. 
* Would you add a dedicated test to cover this part ? I could not find a test explicitly checking accessors (for example `Name()` ?
* Would you modify an interface or create one dedicated to Doc ?

Expose record and field doc

---

schema.go
schema_json_test.go

Fixes `Field.MarshalJSON` handling of default null values. The previous implementation was relying on `omitempty` for the default field and it was not possible to differentiate between a field with no default value and one with `null`. 
Fixes #136

fix: null default when json marshalling unions

---

ocf/ocf.go
ocf/ocf_test.go

From discussion on issue https://github.com/hamba/avro/issues/142
Signed-off-by: Jonas Brunsgaard <jonas.brunsgaard@gmail.com>

Expose Write method on ocf encoder

---

ocf/ocf.go
ocf/ocf_test.go

As mentioned in #142, the Write method should conform to the `io.Writer` interface
Signed-off-by: Jonas Brunsgaard <jonas.brunsgaard@gmail.com>

ocf Encoder should implement writer interface

---

codec_fixed.go
codec_native.go
decoder_union_test.go
encoder_union_test.go

I've used your package to work with BigQuery. It has [`BIGNUMERIC`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types) data type which is encoded to avro as `bytes.decimal`:
So package was not working initially with this data type because it has a scale which overflows `int64` exponent.
This PR adds exponent computation using `big` package instead of `math.Exponent` which allows to work with high scale decimals.

Add support for large scale decimals

---

registry/client.go

Now there is a way to use schemas with references
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions
https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas
```go
const HeaderScheme = `
{
"type": "record",
"name": "eventHeader",
"namespace": "schema",
"fields": [
{ "name": "eventId", "type": "string" }, 
{ "name": "correlationId", "type": "string" },
{ "name": "created", "type": "string" }
]
}`
const EmployeeCreatedAvroScheme = `
{
"type": "record",
"name": "boEmployeeCreated",
"namespace": "schema",
"fields": [
{ "name": "header", "type": "schema.eventHeader"},
{ "name": "userId", "type": "string" }
]
}`
```
1. Register `HeaderScheme`
```go …
```

Schema reference support

---

go.mod
go.sum

Testify >= 1.7.2 contains an issue that breaks go vetting when
using custom test suites: https://github.com/stretchr/testify/issues/1199
This is unfortunately not going to be changed in the v1 branch of
testify.  Since the go-avro module's test suite does not seem to
depend on behaviors of later versions of testify, I would like to
propose reverting to v1.7.1
Signed-off-by: Nathan J. Mehl <n@oden.io>

Revert testify dependency to v1.7.1

---

registry/client.go
registry/client_test.go

Clients desiring to marshal data to [wire format](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format) need access to the id of the schema.
Often times clients will fix their code to a specific version while schema maintainers will continue to develop new versions.
This PR exposes the `GetSchemaInfo` method on the registry client that takes a `subject` and `version` to allow users to subsequently encode to wire format.

patch: added GetSchemaInfo to registry client

---

README.md
codec_union.go
config.go
decoder_union_test.go

When enabled, the union decoder will attempt to resolve the encountered union type. If no decoder is available, the logic falls back to the existing configuration option (error out or return a map).
Fixes #191

feat: Added new config option to support partial union type resolution.

---

ocf/ocf.go
ocf/ocf_test.go

This is useful when one wants a file with *just* the Avro header, for instance in order to convey the schema and no records.
Fixes #196

fix: Flush() should flush underlying avro writer (#196)

---

ocf/ocf.go
ocf/ocf_test.go

feat: specify sync block to an ocf.Encoder (#198)

---

codec_array.go
codec_record.go
decoder_array_test.go

This adds additional context to errors where it was missed. This was pointed out by @nascimento and the original work was done in #177 which seems to have stalled. To improve error handling this should be included in the library though.

fix: add addition error context

---

README.md
codec_enum.go
decoder_enum_test.go
encoder_enum_test.go

This adds support for the `TextMarshaler` and `TextUnmarshaler` interfaces on enums. The implementations of the interfaces must resolve to valid symbols in the schema, otherwise an error will with returned.
Fixes #205

feat: support text marshaler on enum

---

codec_enum.go
decoder_enum_test.go
encoder_enum_test.go

This allows the text marshaler to be on a pointer or non-pointer receiver in enums.
Fixes #205

fix: allow for ptr and non-ptr enum text marshalers

---

README.md
codec_native.go
decoder_native_test.go
encoder_native_test.go

- This supports adds encoding/decoding `uint8` and `uint16` as an Avro `int`, and `uint32` as an Avro `long`.

Added support for unsigned integers

---

codec_union.go
decoder_union_test.go

- updated the union type resolution error to give the union type from the schema that couldn't be resolved. The message when from `"avro: decode union type: unknown union type"` to `"avro: problem resolving decoder for Avro union: avro: unable to resolve type with name test"`. The reason I did this was because I was having a difficult time interpreting the error and had to step through the debugger to see what the problem is.

Improved union type resolution error

---

config.go
config_internal_test.go

This is suggested as disabling cache can sometimes be desired based on the upstream implementation
Fixes #216

feat: Added configuration option to disable encoder/decoder caching layer if needed

---

registry/client.go
registry/client_test.go

This PR adds the `references` parameter to the Registry.IsRegistered(), as per the official [Schema Registry API documentation](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)):
> POST /subjects/(string: subject)
> 
> Request JSON Object:
>  	
> - schema – The schema string
> - schemaType – Defines the schema format: AVRO (default), PROTOBUF, JSONSCHEMA (Optional)
> - references – Specifies the names of referenced schemas (Optional). To learn more, see [Schema References](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas).
> 
Note that this will be a breaking change to the `Registry` interface, as the `IsRegistered()` method signature has changed.
Fixes #221

Add references to `Registry.IsRegistered()`

---

registry/client.go
registry/client_internal_test.go
registry/client_test.go

Wrote code for compatibility level putting and getting. For the testing a bit of guidance would be well accepted! I usually set my tests with a container running, but I couldn't manage to run the whole zookeper+kafka_broker+confluent_schema_registry using [testcontainers-go](https://github.com/testcontainers/testcontainers-go)
Thanks for the attention,
Nuc

Registry compatibility level

---

codec_record.go
decoder_record_test.go
encoder_record_test.go
types_test.go

See first commit for unit tests demonstrating the issues. Run the tests with race detector on (`go test -race`).
Bug 1: the struct encoder and decoder both do nil-check on `ptr` (pointer to top-level struct) rather than `fieldPtr` (pointer to current field) when looking at an struct-embedded pointer.
This was not caught by the test suite because the embedded pointer struct tested is at the top of the struct, so these two variables happen to be the same.
Bug 2: given these types:
```
type Outer struct { *Inner }
type Inner struct { Data [256]byte }
```
if the decoder is decoding an `Outer` and sees a `nil` pointer for `*Inner`, when it tries to allocate a block of memory sized for `Inner` (size 256 bytes), it mistakenly allocates a block sized for `*Inner` instead (size 8), leading to to …

Fix two bugs with unsafe memory access

---

README.md
decoder_fixed_test.go
reader.go

This PR adds support for slab allocation for strings and bytes smaller than 1024 bytes, but will likely be all of them.
This creates a new fast path and centralises the read code, and it is now basically identical.
The benchmarked changes are as follows:
```
name                      old time/op    new time/op    delta
SuperheroDecode-8            281ns ± 0%     245ns ± 2%   -12.81%  (p=0.000 n=8+10)
SuperheroEncode-8            202ns ± 1%     203ns ± 3%      ~     (p=0.255 n=10+10)
PartialSuperheroDecode-8     119ns ± 1%     111ns ± 1%    -6.82%  (p=0.000 n=10+10)
SuperheroGenericDecode-8    1.44µs ± 1%    1.38µs ± 0%    -3.63%  (p=0.000 n=9+9)
SuperheroGenericEncode-8     258ns ± 1%     278ns ± 1%    +7.84%  (p=0.000 n=9+9)
SuperheroWriteFlush-8        167ns ± 1%     169ns ± 1% …
```

feat: use slab allocation for strings and bytes

---

schema.go

This fixes an issue with default validation on Reference Schemas.
Fixes #261

fix: defaults for ref schemas

---

config.go
writer.go
writer_test.go

[#264](https://github.com/hamba/avro/issues/264)

feat: allow array block contain only length

---

schema_parse.go

This allows for skipping the string roundtrip (and 2 copies) if you already have your schema in a `[]byte`.

Add ParseBytes variants for parsing schemas

---

README.md
config.go
reader.go
reader_test.go

This add configuration that sets the maximum size of `bytes` or `string` the reader will create.

feat: add max byte slice size config

---

README.md
codec_fixed.go
decoder_fixed_test.go
encoder_fixed_test.go

This pull request adds the ability to fully express native, uint64 values as fixed-length records within Avro.
See https://stackoverflow.com/a/75242092/151741 for more details.

Ability to serialize uint64 values as fixed-length entries:

---

reader_generic.go
reader_generic_test.go

This fixes an issue with generic reading of Fixed type that returned a byte slice instead of a byte array.
Fixes #285

fix: generic read of fixed

---

cmd/avrogen/testdata/golden_encoders.go
gen/gen.go
gen/testdata/golden_encoders.go

This fixes an issue where generated schema encoders do not cache the schema globally.

fix: cache schema globally

---

decoder_enum_test.go
encoder_enum_test.go
protocol.go
schema_parse.go
schema_test.go

This PR disallows duplicate full names in a single schema. It does not check against external previously cached schemas.
Fixes #295

fix: disallow duplicate names

---

README.md
cmd/avrogen/main.go
cmd/avrogen/main_test.go

Hello, this small PR adds support for stdout output to `avrogen`.
It is implemented by making the `-o FILE` argument optional, writing the generated Go code to stdout if not provided.
I updated the unit tests accordingly and fixed some wrong wording in error messages as well 👍.
The use case for this feature is quick debugging of Go structs generation without having to use temporary files.

feat: add stdout output support to avrogen

---

cmd/avrogen/main.go
cmd/avrogen/main_test.go
gen/gen.go
gen/gen_test.go

Hello, this simple PR adds support for custom initialisms to the `gen` package and `avrogen` command.
Additional custom initialisms are necessary because `strcase.ToGoPascal` only uses GoLint's list of initialisms.
Currently, if an initialism in struct/field names is not part of Golint's, then `strcase` wrongly downcases it.
For example, consider the following schema containing the domain initialism `AID`:
```json
{
"type": "record",
"name": "AIDEventHTTPService",
"namespace": "example",
"fields" : [
{"name": "AIDNumber", "type": "long"},
{"name": "Desc", "type": "string"}
]
}
```
Currently, `avrogen` generates the following Go struct (struct/field names: `AID` -> `Aid`):
```go
package example
// Code generated by avro/gen. DO NOT EDIT.
// AidEventHTTPService is a generated struct.
type …
```

feat: add custom initialisms support to gen package and avrogen

---

cmd/avrogen/main_test.go

While working on PR #302, I realized that the unit tests did _not_ fail when I removed the requirement for `-o FILE`.
The reason is that the unit tests were expecting errors but not _which_ errors. When I removed the requirement for `-o FILE`, the test still passed because `realMain` still failed but for a different reason (schema not found).
This PR fixes the avrogen required flags unit tests by checking the actual exit code returned from `realMain`.

fix: check exit code in avrogen required flags tests

---

cmd/avrogen/main.go
cmd/avrogen/main_test.go
cmd/avrosv/main.go
cmd/avrosv/main_test.go

This PR mainly resolves technical debt left over in avrosv after the improvements in avrogen.
Two chore commits are included:
* chore: rename and rearrange `io.Writer` arguments in avrogen
* chore: improve code and tests in avrosv after avrogen
The first one is to cleanup the ugly `out`/`dumpout` argument names into clearer meanings and logical order.
The second one mostly brings up all the recent unit tests improvements from avrogen into avrosv.
I also added an extra bad schema test case to the avrosv stdout unit test.

chore: codebase cleanup for avrogen and avrosv

---

cmd/avrogen/main.go
cmd/avrogen/main_test.go
gen/gen.go
gen/gen_test.go

Some edge cases require using the tag style from avro as-is for other formats.
The tag style `original` explicitly does not do any processing on the tag before code generation.
This is mostly already supported in the code generation, but the CLI options would reject
any configuration value which would trigger this behaviour.

Allow tag style "original" for additional tags

---

protocol.go
protocol_test.go

Added method `Types` to return Protocol `Types`.
Added method `OriginalString` to return Protocol original schema

Added Types methods to Protocol

---

schema_parse.go

This PR fixes an issue with dereferencing nested circular schemas.
Fixes #318

fix: issue with dereferencing schemas

---

schema_compatibility.go

Change ```checkSchemaName```'s error message from:
**reader schema %s and writer schema %s  names do match**
to:
**reader schema %s and writer schema %s  names do not match**

Fix typo in schema compatibility error message

---

codec_record.go

This PR clarifies the reason `reflect2.PtrOf(field)` is actually a pointer to the field name.

docs: clarify the pointer used

---

codec_map.go
decoder_map_test.go
encoder_map_test.go

This PR adds support to TextMarshaller/TextUnmarshaller for Map keys.
**Note:** For this to work on the decode, the type used must be a pointer in order to implement the TextUnmarshaller interface.
Fixes #327

feat: support TextMarshaller for map key

---

README.md

This short PR fixes an outdated godoc link in the README file.
The previous link was pointing to the older v1 branch of the library.

fix: correct godoc link in README

---

codec_dynamic.go
codec_generic.go
codec_generic_internal_test.go
codec_union.go

This change will make it easier to keep evolving decoders without the need to duplicate a similar change at `reader_generic`.

Move generic decoding to codec level

---

config.go

According to the documentation, set the default value of max byte slice to 1 MiB.
Minor refactoring of the constant's name.
Close #341

Make defaultMaxByteSliceSize equal to 1 MiB

---

codec_enum.go
config_internal_test.go
schema.go
schema_compatibility.go
schema_compatibility_test.go
schema_internal_test.go

fix: enum schema evolution

---

codec.go
codec_dynamic.go
codec_generic.go
codec_generic_internal_test.go
codec_native.go
codec_record.go
codec_union.go
converter.go
converter_test.go

This PR optimises the generic decode.
The benchmarked change is as follows:
```
name                      old time/op    new time/op    delta
SuperheroDecode-8            265ns ± 1%     254ns ± 2%   -4.10%  (p=0.000 n=10+10)
SuperheroEncode-8            201ns ± 1%     201ns ± 1%     ~     (p=0.946 n=9+9)
PartialSuperheroDecode-8     119ns ± 1%     118ns ± 0%   -0.86%  (p=0.003 n=9+9)
SuperheroGenericDecode-8    23.8µs ± 1%     2.1µs ± 0%  -91.23%  (p=0.000 n=10+10)
SuperheroGenericEncode-8     255ns ± 3%     260ns ± 2%   +1.91%  (p=0.004 n=10+10)
SuperheroWriteFlush-8        165ns ± 1%     164ns ± 1%   -0.60%  (p=0.008 n=9+10)
name                      old alloc/op   new alloc/op   delta
SuperheroDecode-8            47.0B ± 0%     47.0B ± 0%     ~     (all equal)
SuperheroEncode-8 …
```

feat: optimise generic decodes

---

reader.go
reader_skip.go
reader_test.go

This PR optimises the `Reader.ReadInt` and `Reader.ReadLong` functions.
The benchmarked change is as follows:
```
name                      old time/op    new time/op    delta
SuperheroDecode-8            265ns ± 1%     244ns ± 1%  -7.95%  (p=0.000 n=10+10)
SuperheroEncode-8            200ns ± 0%     204ns ± 2%  +2.15%  (p=0.000 n=10+10)
PartialSuperheroDecode-8     120ns ± 0%     109ns ± 1%  -9.34%  (p=0.000 n=10+10)
SuperheroGenericDecode-8    23.8µs ± 1%    23.6µs ± 0%  -0.69%  (p=0.000 n=10+8)
SuperheroGenericEncode-8     268ns ± 3%     252ns ± 0%  -6.01%  (p=0.000 n=10+10)
SuperheroWriteFlush-8        164ns ± 1%     164ns ± 0%  +0.43%  (p=0.002 n=9+10)
name                      old alloc/op   new alloc/op   delta
SuperheroDecode-8            47.0B ± 0%     47.0B ± 0%    ~     (all …
```

feat: optimise reading ints and longs

---

codec.go
codec_native.go
config_internal_test.go
schema.go
schema_compatibility.go
schema_compatibility_test.go
schema_internal_test.go

When a schema contains a compatibility change anywhere in its tree, the entire schema should show the change in its fingerprint. To make this simpler, the writer fingerprint is carried in the schema, to show this change. There is an edge case in records that the exact defaults must be accounted for in the cached fingerprint.
This has the benefit of slightly optimising the planning phase.
```
name                      old time/op    new time/op    delta
SuperheroDecode-8            232ns ± 1%     229ns ± 1%  -1.27%  (p=0.000 n=10+10)
SuperheroEncode-8            198ns ± 0%     199ns ± 1%  +0.68%  (p=0.000 n=10+10)
PartialSuperheroDecode-8     106ns ± 0%      97ns ± 1%  -8.05%  (p=0.000 n=8+9)
SuperheroGenericDecode-8    2.17µs ± 0%    2.17µs ± 0%    ~     (p=0.376 n=8+9) …
```

fix: schema compatibility fingerprint

---

schema_compatibility.go
schema_compatibility_test.go

In the Union reader case, we check that the writer schema is compatible with at least one reader schema and resolve the composite schema against the first compatible found one.
We may pass through some incompatible schemas first; we need to explicitly check compatibility for each iteration by calling the `compatible` function (or `Resolve` instead of `resolve`).
The `compatible` function does cache its results, and the added calls will likely hit the cache, so I'm optimistic about the performance :)

Fix: Union reader schema resolution

---

codec_native.go
decoder_native_test.go
encoder_native_test.go

- Ran into a nasty issue where I had incorrectly used a `time.Duration` with a `long` Avro type and `timestamp-millis`. Hamba was encoding the entire int64 for this case instead of erroring on an invalid schema. When Spark/SQL tried to [convert](https://github.com/apache/spark/blob/v3.5.0/connector/avro/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala#L142C38-L142C52) this into a microseconds (it wants everything as micros), it eventually tries to do this:
```
def millisToMicros(millis: Long): Long = {
Math.multiplyExact(millis, MICROS_PER_MILLIS)
}
```
And [Math.multiplyExact](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/Math.html#multiplyExact(long,int)) detects an overflow because it is trying to multiply the long by 1000, which doesn't fit. …

Error on invalid type/logicalType

---

README.md
codec_record.go
codec_union.go
decoder_union_test.go
encoder_union_test.go

This PR adds support for slices directly in nullable unions.
Maps are more complex and will be looked at separately. 
Fixes #371

feat: support slices for nullable unions

---

codec_array.go
decoder_array_test.go

Issue: https://github.com/hamba/avro/issues/373
This PR checks to see if the `size` to allocate the array exceeds the max allocation size. This prevents getting `panic: runtime: allocation size out of range` when decoding arrays with an invalid size.
This is the code to reproduce the error before the fix:
```
package main
import "github.com/hamba/avro/v2"
func main() {
rawSchema := []byte("{\"items\":{\"type\":\"boolean\"},\"type\":\"array\"}")
schema, _ := avro.ParseBytes(rawSchema)
data := []byte("\x02\x00\xe9\xe9\xe9\xe9\xe9\xe9\xe9\xe9\x00")
var container any
avro.Unmarshal(schema, data, &container)
}
```
This is the [line of code](https://github.com/hamba/avro/blob/7a2eb5fdc5a4c5abf9712c0e12c3806691f866d5/codec_array.go#L54) that leads to the error. The size is 29787588086545014 …

Check for max allocation

---

codec_array.go
config.go
decoder_array_test.go

I introduced the `defaultMaxSliceAllocSize` config for security reasons, similar to `Config.MaxByteSliceSize` introduced in this [PR](https://github.com/brianshih1/avro/commit/b4a402f41cf44b6094b5131286830ba9bb1eb290).
I need a way to prevent the array decoder from consuming too much memory for my application, the `defaultMaxSliceAllocSize` is the limit for how much memory the `arrayDecoder` can allocate.
Let me know if you think I should just reuse `MaxByteSliceSize` instead of introducing a new config.

feat: add max slice alloc size config

---

codec_array.go
codec_map.go
decoder.go
decoder_array_test.go
decoder_map_test.go

This fixes an issues were short-reads on maps and arrays are not returned.
Fixes #377

fix: handle short read errors on arrays and maps

---

codec_skip_test.go
decoder_native_test.go
decoder_test.go
ocf/ocf.go
reader.go
reader_test.go

This ensures that short reads (unexpected EOF) returns errors properly in the reader.

fix: reader returns errors on unexpected EOF

---

decoder_native_test.go
reader.go

This ensures that readByte (unexpected EOF) returns errors properly in the reader.

fix: readByte returns errors on unexpected EOF

---

reader.go
reader_test.go

This fixes an issue that occurs when ReadInt/Long encounter an error across a buffer boundary, causing `r.head` to be greater than `r.tail`.

fix: reader int/long setting head > tail

---

codec_generic_internal_test.go
codec_union.go

According to the [Avro spec](https://avro.apache.org/docs/1.11.1/specification/#unions-1) for binary encoding of Union types, a union is encoded by first writing an int value.
However, the current decoder uses `ReadLong` instead of `ReadInt`, which causes some errors when `ReadInt` and `ReadFloat` returns different values.

fix: Union Decoder uses readInt

---

config.go
config_386.go
config_x64.go

The Apache Arrow project uses this library for supporting reading Avro into Apache Arrow record batches. A dependabot alert to update to a new version fails building in the CI due to usage of `int(1 << 48)` which fails on the cross-build CI for 32-bit systems [link](https://github.com/apache/arrow/actions/runs/8881814891/job/24385052137?pr=41438).
If we explicitly type it as an `int64` this alleviates the problem and allows this library to continue to successfully build on 32-bit systems.

fix: 32bit build fails

---

pkg/crc64/crc64.go
schema.go
schema_canonical_test.go
schema_compatibility_test.go
schema_internal_test.go
schema_json_test.go
schema_test.go

This PR makes the schema table tests parallel, where possible. This unearthed a race in `FingerprintUsing` which has also been fixed.

feat: make schema tests parallel

---

noescape.go

Go plans to lock down `go:linkname`. The only use in `avro` is `noescape` which can be moved to the module.

fix: remove go linkname

---

ocf/codec.go
ocf/codec_test.go

Addressing issue https://github.com/hamba/avro/issues/419
benchmark results always creating a new zstd encoder/decoder
```
goos: linux
goarch: amd64
pkg: github.com/hamba/avro/v2/ocf
cpu: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
BenchmarkZstdEncodeDecodeLowEntropyLong
BenchmarkZstdEncodeDecodeLowEntropyLong-8    	     289	   3523847 ns/op	10891887 B/op	      40 allocs/op
BenchmarkZstdEncodeDecodeHighEntropyLong
BenchmarkZstdEncodeDecodeHighEntropyLong-8   	     298	   3390952 ns/op	10894703 B/op	      40 allocs/op
```
benchmark results reusing an existing zstd encoder/decoder
```
BenchmarkZstdEncodeDecodeLowEntropyLong
BenchmarkZstdEncodeDecodeLowEntropyLong-8    	   55628	     22883 ns/op	   19220 B/op	       2 allocs/op
BenchmarkZstdEncodeDecodeHighEntropyLong …
```

feat:  Improve zstd encoder and decoder usage in the compressor codec

---

README.md
codec_native.go
decoder_native_test.go
encoder_native_test.go

This PR adds support for handling Go `int` types using the Avro type `long`. Note that decoding is only allowed on 64-bit systems, to ensure safety.
Fixes https://github.com/hamba/avro/issues/421.

Support for Go `int` encoding/decoding into/from Avro `long`

---

codec_default_internal_test.go
codec_fixed.go
codec_generic.go
codec_native.go
decoder_fixed_test.go
decoder_native_test.go

This fixes the issue with Fixed Decimals not being able to be decoded into the struct they were encoded from. This stems from an issue with `*big.Rat` decoding.
Fixes #424

fix: decimal decoding into *big.Rat

---

codec_record.go
decoder_record_test.go

This fixes a potential bug where map record decodes where optimised changing how unions are decoded. 
See https://github.com/hamba/avro/commit/aa7f619fd2c0362a8b649c4d7b7f0d3317bb69dd#diff-76d79b5f35aac6861a49a410fbb009f12801faadce2db0f35d21f4c50bfe3796R279
Fixes #386

fix: map record decodes in union case

---

.github/workflows/test.yml
.golangci.yml
README.md
go.mod
reader.go

This adds support for Go 1.23, removing support for Go 1.21.

chore: support go 1.23

---

schema_parse.go
schema_test.go

This references previously dereferenced schemas when parsing.
There is an edge case, where in multiple parse calls, a schema has been dereferenced twice. If this ends up in the same schema, the second "copy" needs to be re-referenced.
Fixes #437

fix: ref already seen schemas in deref walk

---

.github/workflows/test.yml
config_arm.go
config_x64.go

This fixes an issue where `arm` is using 64 bit config, even though it is a 32 bit system.
Fixes #439

fix: exclude arm from x64 config

---

codec.go
codec_default.go
codec_native.go
schema_compatibility_test.go

#368 related
The previous fix made a restriction to prevent accepting `int64` as a Go type for the Long-timestamp codec. However, this restriction affected the `defaultDecoder` when dealing with the JSON-decoded default value represented as `int64`.
A solution could be:
1 - Improve the default JSON decoding to ensure that the default value is correctly represented as `time.Time`.
2- Relax the restriction made in the previous fix and limit it to the case of `time.Duration`.
The PR draft presents these solutions, and a test has been added to cover this case.

fix: Long timestamp default decoding

---

codec_record.go
schema_compatibility_test.go

I think I overlooked an edge case the last time I worked on schema evolution:
If a field is missing in both the binary and the reader struct, it should be ignored rather than calling skipDecoder (which technically performs a read and moves the cursor).
The current implementation might perform a dirty read, causing errors like:
> unexpected EOF
> ReadString: size is greater than `Config.MaxByteSliceSize`

Fix: decode in the case of field missing in both writer binary and reader struct.

---

.github/workflows/test.yml
.golangci.yml
codec_fixed.go
codec_map.go
codec_record.go
codec_skip.go
go.mod
go.sum
pkg/crc64/crc64.go
reader_generic.go
schema.go

This bumps the minimum Go version to v1.22 to allow other dependencies to be updated. It subsequently fixes new linter issues that come with the Go version change.

chore: bump min Go version

---

protocol.go
protocol_test.go
schema_parse.go
schema_test.go

The Avro spec has changed to allow empty namespaces as null namespaces:
> A namespace is a dot-separated sequence of such names. The empty string may also be used as a namespace to indicate the null namespace.
This PR adjusts validations and tests to allow support this new spec case.
Fixes #457

feat: allow empty namespaces

---

ocf/ocf.go
ocf/ocf_test.go

Currently, the OCF Decoder will fail when parsing OCF files that contain a field that exceeds the default limit of 1MiB. There is currently no way to configure this limit for the OCF Decoder.
This change provides a way to construct an OCF Decoder using a custom avro.API, which enables configuration of the decoder.

feat: allow passing in custom options for OCF decoder.

---

ocf/ocf.go
ocf/ocf_test.go
ocf/testdata/full-schema.json
schema.go

There are a few issues when dealing with dynamic types:
1. The existing code _always_ uses `avro.DefaultSchemaCache` when parsing schema JSON documents. But this pollutes a global variable with temporary, non-global state. If the schemas being processed have a high cardinality of distinct namespaces and/or types, this could be a memory pressure issue, since none of the cached schemas are ever purged.
2. The existing code requires a JSON document for the schema, but when dynamically building a schema, an `avro.Schema` is more natural and more type-safe.
3. The existing code stores the schema in the file's "avro.schema" metadata key using the output of `Schema.String()`. However, this schema _omits_ a lot of the schema details: in particular, it drops logical types and extra properties. I …

Improve OCF encoder/decoder handling of dynamic types

---

gen/testdata/golden.avsc
ocf/ocf_test.go
ocf/testdata/full-schema.json
schema.go
schema_json_test.go
schema_parse.go
schema_test.go

This updates the parsing of schema JSON documents and the way properties are possibly discarded (to avoid problematic properties that conflict with proper fields of a type and could result in invalid JSON if included when marshaling to JSON).
The tests now demonstrate that all properties and logical types are preserved as extra properties, even for unrecognized and incorrectly configured logical types, even for null types.
> Just a note, in the parser, it should not be needed to add LogicalType where it does not naturally exist, and it will be added to Props as part of the `,remain`.
I added these everywhere so that this property would be properly type-checked: if it is present, it should be a string. So now this will surface as an error if it's not a string, even for an "array" or …

Preserve unrecognized logical types and properties

---

ocf/codec.go
ocf/codec_test.go
ocf/ocf.go
ocf/ocf_test.go

Currently the ZStandard codec is used with its default settings, which in some cases are less than optimal.
This change allows setting options in the codec to configure it according to needs.

feat: allow setting zstd codec options

---

ocf/ocf.go

Issue is with files having no data (file attached in zip)
File is from Google Cloud Platform. 
[empty_set.zip](https://github.com/user-attachments/files/18522805/empty_set.zip)

fix: add handling to skip block data in Decoder readBlock method

---

pkg/crc64/crc64.go
pkg/crc64/crc64_test.go
schema.go
schema_test.go

The Avro specification details a Single Object Encoding using a header
to associate a schema ID with an Avro payload. The ID is defined as the
CRC64 fingerprint in little-endian encoding.
The pkg/crc64 module only provides big-endian CRC64, and the CRC64-AVRO
fingerprint type is implemented as such. The specification does not
detail endianness of the CRC64-AVRO fingerprint itself (only when
embedded in an SOE header).
To avoid breaking existing CRC64-AVRO fingerprints, add a new
fingerprint type CRC64-AVRO-LE, identical to CRC64-AVRO except
little-endian.
Add NewWithByteOrder and SumWithByteOrder top-level functions to crc64
so users can configure the hasher to use a specific byte order.
Add tests and benchmarks for the SumWithByteOrder function.
Fixes #489.

feat: add CRC64-AVRO-LE fingerprint type

---

gen/gen_test.go
gen/output_template.tmpl

There is a problem when generating Go code with encoders and full schema. If The schema has some backticks in doc string, then it will produce invalid Go code, because the schema JSON string is wrapped in backticks (``` ` ```). This needs backtick escaping.

fix(gen): escape backticks

---

codec.go
codec_generic.go
codec_generic_internal_test.go
codec_native.go
decoder_record_test.go
encoder_record_test.go

This fixes an panic when a `Null` schema is encoded or decoded.
Fixes #432

fix: panic on null type

---

.golangci.yml

This removes the deprecated `deadline` config for the linter.

chore: remove deprecated linter deadline

---

codec_array.go
codec_union.go
decoder_array_test.go
decoder_union_test.go
encoder_union_test.go

Fix handling of empty and nil slices.  There are scenarios where empty slices get turned into slices of 1 element, and where nil slices cause a panic.
This PR fixes these scenarios.
Added unit tests that demonstrate various scenarios, some of which fail before the fix and pass with the fix.
Notably:
* `TestDecoder_UnionInterfaceArrayEmpty`
* empty array of ints in union decoded as a slice of int with 1 element instead of empty slice
* `TestDecoder_UnionArrayRecordEmpty`
* empty array of records in union decoded to non-nil pointer to nil slice as nil slice instead of empty slice
* `TestDecoder_UnionInterfaceArrayRecordEmpty`
* empty array of records in union decoded as a slice of records with 1 element instead of empty slice
* `TestEncoder_UnionInterfaceUnregisteredArrayNull`
* encoding a …

fix: empty and nil slice handling

---

.github/workflows/test.yml
.golangci.yml

This bumps golangci-lint to v2

chore: bump golangci-lint to v2

---

README.md
codec_dynamic.go
codec_fixed.go
codec_native.go
config.go
typeconverter.go
typeconverter_test.go

Add the ability to register type conversion functions when using `any` in Go with the underlying Go type not compatible with the corresponding field's Avro type.
Fixes #509 
Added unit tests that demonstrate various scenarios.

feat: add data type conversion for generic encoding/decoding

---

cmd/avrogen/main.go

In case of struct generation from schema registry entries, we can pass not only numerical versions, but also a 'latest' version.
Manual test with local schema registry.
```
/home/ekazakas/.cache/JetBrains/GoLand2024.3/tmp/GoLand/___go_build_github_com_hamba_avro_v2_cmd_avrogen -pkg test -schemaregistry http://localhost:8081 print_report:latest #gosetup
// Code generated by avro/gen. DO NOT EDIT.
package test
// PrintReport is a generated struct.
type PrintReport struct {
ID   int    `avro:"id"`
Ref  string `avro:"ref"`
Flag int    `avro:"flag"`
}
Process finished with the exit code 0
```
```
/home/ekazakas/.cache/JetBrains/GoLand2024.3/tmp/GoLand/___go_build_github_com_hamba_avro_v2_cmd_avrogen -pkg test -schemaregistry http://localhost:8081 print_report:1 #gosetup
// Code generated by …
```

feat(cli): add possibility to fetch latest schema from schema registry

---

codec_dynamic.go
codec_union.go
schema.go
typeconverter.go
typeconverter_decode_test.go
typeconverter_encode_test.go
typeconverter_test.go

Extends #515 to allow type conversions for Avro Unions when encoding/decoding Go `any`.
Added more unit tests (and split the unit test file into separate files for encode and decode).
Benchmark comparison (10 runs each) looks good; any differences are just noise:
```
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │
SuperheroDecode-12          595.6n ±  7%   626.1n ±  8%        ~ (p=0.063 n=10)
SuperheroEncode-12          612.3n ±  7%   508.7n ± 27%  -16.91% (p=0.043 n=10)
PartialSuperheroDecode-12   289.9n ± 16%   262.2n ± 13%   -9.54% (p=0.011 n=10)
SuperheroGenericDecode-12   8.184µ ± 29%   9.004µ ± 10%        ~ (p=0.143 n=10)
SuperheroGenericEncode-12   1.054µ ±  5%   1.030µ ± 12%        ~ (p=0.565 n=10) …
```

feat: add data type conversion for generic encoding/decoding unions

---

registry/client.go
registry/client_test.go

Confluent Schema Registry supports tags, metadata, and rules, which together support the concept of a [Data Contract](https://docs.confluent.io/platform/7.9/schema-registry/fundamentals/data-contracts.html).
This change adds support only for [metadata properties](https://docs.confluent.io/platform/7.9/schema-registry/fundamentals/data-contracts.html#metadata-properties) that may include arbitrary information about the schema, such as who created it:
```json
{
"schema": "...",
"metadata": {
"properties": {
"owner": "Bob Jones",
"email": "bob@acme.com"
}
}
}
```
Properties may also include [major schema version](https://docs.confluent.io/platform/7.9/schema-registry/fundamentals/data-contracts.html#application-major-versioning) to highlight incompatible changes throughout the schema …

feat(registry): add schema metadata properties to schema info

---

schema_parse.go

This avoids a two unneeded copies of the input data, at least with the code as read (it's unclear if the compiler would optimize this away).
Memory optimization (or at least better use of functionality that already exists).
`go test`

ParseFiles: avoid avoidable allocation

---

codec_record.go

- Fix struct tag parsing to handle comma-separated tag values correctly
- Parse only the field name portion before the first comma (e.g., `avro:"field_name,omitempty"` → field name is `field_name`)
- This follows Go's standard convention for struct tags
- Added `strings.Cut()` to extract only the field name before the comma
- Previously the entire tag value including options was incorrectly used as the field name

fix: parse struct tag field name correctly

---

schema_compatibility.go
schema_compatibility_test.go

This fixes an issue with Enum schema compatibility, where non-identical schemas would decode incorrectly.
Fixes #556
Added a test.

fix: enum schema compatibility

---

.github/workflows/test.yml
.golangci.yml
go.mod
schema.go

This bumps Go support to 1.24 and 1.25

chore: support Go 1.25
